language: node_js
node_js:
  - "6.11.2"
sudo: false
branches:
  only:
    - master
    - /^fix-.*$/
    - /^issue-.*$/
before_script:
  - npm install -g bower
  - npm install
  - bower install --force
  - npm run build
after_success:
  - npm run coveralls
