language: node_js
node_js:
  - "0.12"
sudo: false
branches:
  only:
    - master
    - /^fix-.*$/
    - /^issue-.*$/
before_script:
  - bower install
  - npm run build
after_success:
  - npm run coveralls
